### ISSUE TITLE
reset option not recognized by trade.sh script

### ISSUE THREAD

**Issue by rcaballeron** [HyperledgerHandsOn/trade-network#12]
The trade.sh script does not recognized the **reset** command. I think that the problem is located in the section "Parse commandline args" (line 1348) because the **reset** command is not parsed there.

```
if [ "$MODE" == "up" ]; then
  EXPMODE="Starting network"
elif [ "$MODE" == "down" ]; then
  EXPMODE="Stopping network"
elif [ "$MODE" == "restart" ]; then
  EXPMODE="Restarting network"
elif [ "$MODE" == "clean" ]; then
  EXPMODE="Cleaning network and channel configurations"
...
```

**Comment by VRamakrishna** [comment]
No, the section in your comment above is used only to assign values to variable. Here is the line where the `reset` command is applied: https://github.com/HyperledgerHandsOn/trade-network/blob/master/bash/trade.sh#L1476.

What error are you getting?

**Comment by rcaballeron** [comment]
Hi,
Yes, and this is the issue if I'm not wrong, in the aforementioned block the option `reset`
is not detected and the line [1409](https://github.com/HyperledgerHandsOn/trade-network/blob/master/bash/trade.sh#L1409) is executed

As result, the command help is printed out.

**Comment by VRamakrishna** [comment]
Ahh......you are right. I'll fix this soon. To get past this, you can add an `if` for `reset` to guard against the help being printed.
