### ISSUE TITLE
Chapter 4 - utils directory is referenced as scripts directory

### ISSUE THREAD

**Issue by rcaballeron** [HyperledgerHandsOn/trade-network#13]
In the book, in Chapter 4, the `utils`(https://github.com/HyperledgerHandsOn/trade-network/tree/master/bash/utils) directory is referenced as `scripts`.

**Comment by rcaballeron** [comment]
BTW, I don't know if this is the right place for reporting about such topics

**Comment by VRamakrishna** [comment]
I see it. We used `scripts` as a placeholder in the early stages of the project and renamed the folder to `utils` later. Thanks for pointing this out. I'll try to get in touch with the publisher.

It's perfectly fine to draw our attention to errors here. Alternatively, you can also email the publisher, who in turn will get in touch with us.

**Comment by VRamakrishna** [comment]
Added a note in the [Errata Wiki](https://github.com/HyperledgerHandsOn/trade-network/wiki/Errata) for our readers and users. Thanks for pointing it out!
