### ISSUE TITLE
"Client sent an HTTP request to an HTTPS server."

### ISSUE THREAD

**Issue by LiuhahaLuck** [HyperledgerHandsOn/trade-network#16]
Hey, when I depoly this program locally and open"localhost:7054", broworse tell me "Client sent an HTTP request to an HTTPS server."
What's happend?

**Comment by VRamakrishna** [comment]
It's an HTTP server, configured to communicate only using TLS. You can see this in the URLs in the connection profiles (`https://localhost:7054`, etc.)

If you specify `https://localhost:7054` in a browser, that ought to work, but it won't serve any purpose. What you ought to do is follow the instructions and run the scripts, which underneath do hit this server, but at specific URLs.
