### ISSUE TITLE
M1 Mac Support

### ISSUE THREAD

**Issue by SecKatie** [HyperledgerHandsOn/trade-network#7]
The instructions as provided in the book do not work on M1 Macs.

The Issues appear to arrive with the inclusion of fabric-ca. Is it possible to run the project without this requirement?

**Comment by VRamakrishna** [comment]
@JoshuaMulliken Can you elaborate on how precisely the instructions do not work?

FYI, yes, the Fabric-CA is a mandatory requirement. I'm not sure which instructions you are referring to, but if you are talking about the cloning and building of the Fabric and Fabric-CA repos (`make docker`), those are optional (as is mentioned in the book). You can directly pull images from Docker Hub if they exist for your platform instead. To do this, you can directly jump to the trade network bash scripts. Of course, if those shell scripts don't run on your OS, they'll have to be adapted suitably.

@ldesrosi Can you help out or advise Joshua?

**Comment by SecKatie** [comment]
The problem is that fabric-ca does not have an arm64 build on dockerhub and the `make docker` command fails

<img width="682" alt="CleanShot 2021-02-18 at 00 22 06@2x" src="https://user-images.githubusercontent.com/36283247/108309336-5e313300-717f-11eb-8105-6ab0c1930b7c.png">

**Comment by ldesrosi** [comment]
@JoshuaMulliken a number of our components rely on fabric-ca being available to register and enrol identities.  

Unfortunately, without the Hyperledger Fabric community supporting that architecture, it would be hazardous to attempt to make it work with arm64.  Furthermore, just adding to the challenge, we do have access to an M1 Mac.

**Comment by SecKatie** [comment]
Hey, I found a way to get the images running through the trade.sh script.

Docker on M1 supports the `platform: linux/amd64` syntax in docker-compose so I was able to add a directive into the `trade.sh` `if [[ "$OSTYPE" == "darwin"* ]] && [[ $(uname -m) == arm* ]]; then` to detect if it is an arm mac and then it will load the new docker-compose files that include the platform directive. You can see this here: https://github.com/JoshuaMulliken/trade-network

**Comment by SecKatie** [comment]
I have created this pull request: https://github.com/HyperledgerHandsOn/trade-network/pull/8

**Comment by ldesrosi** [comment]
Hello @JoshuaMulliken ,

Thank you very much for the pull request.  I ended up taking a slightly different approach and adding a `PLATFORM` variable to the docker-compose file.  The `.env` file contains the default value `linux/amd64` which works for Ubuntu, Mac Intel and Mac M1.

I wanted to avoid duplicating all of the YAML files as it would have made it hard to keep them in sync afterwards.
Once @VRamakrishna reviews PR #9, you should be able to provision the network without issue.

In testing, I also picked up an issue with Docker v3 and the UNIX socket used to talk to the underlying Docker Engine to deploy the chaincode container.  It will also be fixed once the PR is reviewed and merged.

Let us know if you encounter further issues.

I will go ahead and close your PR, but we really appreciated you taking the time to submit the PR.

**Comment by VRamakrishna** [comment]
@JoshuaMulliken Luc's PR is merged to master. Can you confirm it works on your system, and close this issue?

**Comment by SecKatie** [comment]
It is tested and working! Thank you!
